/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

const bGround = require('fcc-express-bground');
const myApp = require('./myApp');
const express = require('express');
const app = express();

if (!process.env.DISABLE_XORIGIN) {
    app.use((req, res, next) => {
        const allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
        const origin = req.headers.origin || '*';
        if (!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1) {
            console.log(origin);
            res.setHeader('Access-Control-Allow-Origin', origin);
            res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
        }
        next();
    });
}


myApp.use(function (req, res, next) {
    console.log(req.method, req.path, req.ip);
    next();
})

myApp.get("/", function (req, res) {
    console.log(__dirname)
    res.sendFile(__dirname + "/views/index.html")
})

// 提供静态文件服务,通过/public/文件民 访问public目录下的文件
myApp.use("/public", express.static("public"))

myApp.use("/now", function (req, res, next) {
    req.Time = new Date().toString()
    next()
}, function (req, res) {
    res.send({time: req.Time})
})
myApp.get("/json", function (req, res) {
    if ("uppercase" === process.env.MESSAGE_STYLE) {
        res.json({"message": "Hello json"})
    } else {
        res.json({"message": "Hello JSON"})
    }
})


myApp.get("/:word/echo", function (req, res) {
    res.send({echo: req.params.word})
})


myApp.get("/name", function (req, res) {
    res.send({name: req.query.first + ' ' + req.query.last})
})

myApp.post("/name", function (req, res) {
    var string = req.body.first + " " + req.body.last;
    res.json({name: string});
});


const port = process.env.PORT || 3000;
bGround.setupBackgroundApp(app, myApp, __dirname).listen(port, () => {
    bGround.log(`Node is listening on port ${port}...`);
});

/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

